### PR TITLE
Audio Player

### PR DESCRIPTION
**Pull request by se3000**
Add a little style to the audio player. Hooks it up to auto play live stream or fallback to a randomly picked show. Displays show and episode name.

Play/pause button works but waiting for a pause icon.

Includes moving some config variables into environment variables.

### CODE REVIEW

**Comment by omnikrll** [comment]
There's play & pause buttons in the Bootstrap glyphicon set: http://getbootstrap.com/components/#glyphicons

**Comment by se3000** [comment]
Awesome! Thanks. Just pushed it to staging.

Also added defaulting the name to a date in the serializer.

**Comment by se3000** [comment]
@mikekaminsky can you test this out on staging and merge when you get a chance?

**Comment by mikekaminsky** [comment]
Will do today!

**Comment by mikekaminsky** [comment]
@se3000 looks like something weird is going on with the assets. Both locally and on staging the player isn't working right (see attached). 
screen shot 2016-05-08 at 10 14 50 am

**Comment by se3000** [comment]
Oh, bummer. I don't get that. What browser are you using?

**Comment by mikekaminsky** [comment]
Chrome!

**Comment by se3000** [comment]
Weird, was getting it in Firefox but not Chrome. Switched to another method of error handling which seems to be supported by more browsers, but leaves a little error message in the console... Good thing no one checks there.

**Comment by mikekaminsky** [comment]
Everything looks good and works local. Logo is missing from staging -- did you deploy there?

**Comment by se3000** [comment]
fixed

**Pull request merged**
