### PR TITLE
Support livestream

### PR DESCRIPTION
**Pull request by idbentley**
This pull request adds support for the shoutcast livestream.

I wasn't able to get this working with the audiojs library, and I can't find any examples of people doing so successfully, so I changed the library to mediaelement js (mediaelementjs.com/), which has a relatively crappy API, but seems to work well for these cases.

I didn't add any checking for online-ness of the stream.

The stream doesn't auto-play, and for now there's an unstyled link at the top of the page to start playing the stream.

I made the semantics of using this tool pretty similar to Soundcloud, where if you click around to other episodes, the stream will still play until you click play on a different episode.

This will be a lot more intuitive when things are styled better, and the player is built into the UI.

Another outstanding issue is that while playing the stream the player shows the time as NaN.  Not a big deal, but not ideal either.

### CODE REVIEW

**Comment by idbentley** [comment]
Logic changes are all in the first commit.  The 1,000,000 vendor file changes that come from replacing the javascript library are in the second commit.

**Comment by omnikrll** [comment]
+1

**Comment by omnikrll** [comment]
+1

**Comment by se3000** [comment]
Nice. Looks like a much more robust player.

**Pull request merged**
