### PR TITLE
Edit shows

### PR DESCRIPTION
**Pull request by mikekaminsky**
I think I did it? This should add the ability to edit show name and url.

I think I'm finally starting to grok this rails/angular combo!

### CODE REVIEW

**Comment by mikekaminsky** [comment]
@se3000 ^^

**Comment by se3000** [comment]
Nice! Looks like you're getting it, this touched a little bit of everything, routes, serializers, even tests!

Ran the tests, all looks good. Merging.

**Comment by mikekaminsky** [comment]
What's the next thing to work on? I started looking at media players but couldn't figure out how to really get started...

**Comment by se3000** [comment]
Good question. I think styling and the mp3 player are really the big things
left to do... there's probably other nice to have features, but I think
getting those done first would be best.

One optimization comes to mind already too, around the shows index page.
Pulling back every show pulls back every episode with it... probably not
necessary.

**Comment by mikekaminsky** [comment]
Awesome. I might try to grab the show index optimization if I have a block
of time.

For styling, should we try to loop Karl in and see if he wants to jump in?
Think we are at a good enough place, or do we need more infrastructure for
that to be productive?

**Comment by se3000** [comment]
Looping Karl in seems like a good idea. If there's any CSS frameworks he's
hoping for we can start to figure out how to include them.

For the show index optimization I would make a different Serializer, like
"ShowPreviewSerializer" the main thing is not having the "has_many
:episodes" association.

**Pull request merged**
