### PR TITLE
Responsive Styles for Home Page & Show Detail Page

### PR DESCRIPTION
**Pull request by omnikrll**
Also includes implementation of the side nav and some updates to the Shows page. The dynamic masonry grid layout from the original design will take more work to implement but now at least it looks a bit closer.

### CODE REVIEW

**Comment by mikekaminsky** [comment]
@omnikrll did you change the fonts? It looks like we're still seeing helvetica on staging:
http://stark-bastion-37166.herokuapp.com/#/

**Comment by mikekaminsky** [comment]
@omnikrll also, I think the nav menu still isn't working? The font issue could be with Heroku asset pipeline, so just let me know if you expected something different than you see on staging and I can try to debug. [This might be the issue with the fonts](http://stackoverflow.com/questions/19323563/heroku-font-assets-not-working)

**Comment by omnikrll** [comment]
I think it's the asset pipeline. Fonts and scripts were workin for me
locally, in both browser and iOS simulator

**Comment by mikekaminsky** [comment]
Boom! changing to font-url fixed it. Fixed the fonts at least. Nav still isn't working on staging.

**Comment by mikekaminsky** [comment]
Okay so nav still isn't working on staging. I can try to do some more debugging tonight, definitely something with the asset pipeline. I'll fuck around, but might have to add a bunch of ugly commits since I can only test by pushing :/

**Comment by mikekaminsky** [comment]
(But otherwise this is looking fucking awesome @omnikrll !!!!!)

**Comment by se3000** [comment]
I'll check out the asset thing soon.

**Comment by se3000** [comment]
Awesome work @omnikrll!

**Comment by omnikrll** [comment]
thanks guys!! let me know when this is good to go!

**Comment by mikekaminsky** [comment]
@omnikrll @se3000 I got it working by changing how the javascripts are compressed. Karl, can you do some QA-testing on staging and make sure everything is working as you'd expect? Once you give the thumbs up, I'll merge this branch and push to production.

**Comment by mikekaminsky** [comment]
Nice. LGTM

**Comment by mikekaminsky** [comment]
Pushing to staging and production...now

**Pull request merged**
